namespace Windows.UI.Xaml;

public enum AutomationTextAttributesEnum
{
	AnimationStyleAttribute = 40000,
	BackgroundColorAttribute,
	BulletStyleAttribute,
	CapStyleAttribute,
	CultureAttribute,
	FontNameAttribute,
	FontSizeAttribute,
	FontWeightAttribute,
	ForegroundColorAttribute,
	HorizontalTextAlignmentAttribute,
	IndentationFirstLineAttribute,
	IndentationLeadingAttribute,
	IndentationTrailingAttribute,
	IsHiddenAttribute,
	IsItalicAttribute,
	IsReadOnlyAttribute,
	IsSubscriptAttribute,
	IsSuperscriptAttribute,
	MarginBottomAttribute,
	MarginLeadingAttribute,
	MarginTopAttribute,
	MarginTrailingAttribute,
	OutlineStylesAttribute,
	OverlineColorAttribute,
	OverlineStyleAttribute,
	StrikethroughColorAttribute,
	StrikethroughStyleAttribute,
	TabsAttribute,
	TextFlowDirectionsAttribute,
	UnderlineColorAttribute,
	UnderlineStyleAttribute,
	AnnotationTypesAttribute,
	AnnotationObjectsAttribute,
	StyleNameAttribute,
	StyleIdAttribute,
	LinkAttribute,
	IsActiveAttribute,
	SelectionActiveEndAttribute,
	CaretPositionAttribute,
	CaretBidiModeAttribute
}
